### ISSUE TITLE
Some build issues in ubuntu-20.04 with ros-noetic

### ISSUE THREAD

**Issue by TwooSix** [chutsu/yac#2]
When I try to use `make deps` to install dependencies, it prompts that the script only supports Ubuntu 22.04. However, I noticed that your repository was built in Ubuntu 20.04 initially. I attempted to modify the variable in `deps/scripts/config.bash` to make it work, but I am unsure if it is compatible.

After installing the dependencies, I typed `catkin build -DCMAKE_BUILD_TYPE=Release yac yac_ros`, which resulted in the following error:
```
[build] Error: Given package 'yac' is not in the workspace and pattern does not match any package
```
Furthermore, I tried to build yac alone using cmake:
```
cd yac
mkdir build && cd build
cmake .. -DCMAKE_BUILD_TYPE=Release
make -j
```
However, I encountered another error:
```
In file included from /home/ls/catkin_ws/src/yac/yac_ros/src/ros_utils.cpp:1:
/home/ls/catkin_ws/src/yac/yac_ros/src/ros_utils.hpp:39:10: fatal error: yac/yac.hpp: No such file or directory
   39 | #include "yac/yac.hpp"
```
Is there any better solution? Thanks!

**Comment by chutsu** [comment]
Apologies for the late reply, by default don't subscribe to github issues...

1. I dont know if the repo will work with ros-noetic since I try to develop on the latest ROS version (currently on humble at the moment)
2. Given that I struggled to get libyac available for ros packages, I have decided to create a `/opt/yac` when the user does a `sudo make install` doing this will enable the `yac_ros` to find `/opt/yac/lib/libyac.so`.
3. If you just want to play around with yac, I have created a `[DockerFile](https://github.com/chutsu/yac/blob/master/Dockerfile)` for it:

**Comment by chutsu** [comment]
May I ask what you would like to test?

**Comment by chutsu** [comment]
Hey @TwooSix, may I ask what you would like to test?

**Comment by TwooSix** [comment]
> Hey @TwooSix, may I ask what you would like to test?

Oh, I'm sorry, I didn't get around to testing the code build based on your reply right away because I got tied up with other stuff.
I just wanna check if YAC works as described in your paper, like if it really can help the students who are beginners calibrate the camera more easily and conveniently as you've mentioned

**Comment by chutsu** [comment]
I would claim yes, it does help, but it has been a long time and I have somewhat lost interest in maintaining the _**interactive part**_ alive for the general to use. Because:

1. It is very hardware specific (I used the Intel D435i RealSense)
2. Target size dictates the size of the motions you have to achieve
3. I'm just a PhD trying to finish up and lack the time

I understand the I should make this reproducible, but my current priority is to finish up. I will try to fix this, but I cannot give any guarantees, I hope you understand.

On a side note, the offline versions of this tool compares quite competitively to Kalibr so ...
